services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL
    command: bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: studentpass
      MYSQL_DATABASE: php_course
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: studentpass
    depends_on:
      - mysql

volumes:
  mysql_data: